### ISSUE TITLE
Very slow folder lookup

### ISSUE THREAD

**Issue by anjos** [RhetTbull/PhotoScript#36]
I'm using this package to re-arrange albums from a deep folder structure into a shallower one, like so:

`Folder A -> Folder B -> Folder C -> Album` >>> `Folder A -> Folder B -> Album`

This happened because I'm importing my photos into the Photos App using the "Keep Folder" checkbox.  By default, if your photos are organised in events split by year and month, then this is the outcome (`Folder A` is the year, `Folder B` is the month, and finally `Folder C` is the event, containing a single album with the photos of the original folder).

I have a large amount of photos and events, therefore, I will end-up with lots of `Folder C`-type folders with a single album inside.  I'd like to use PhotoScript to a) move the single album inside `Folder C` up to `Folder B`, then b) delete `Folder C`.

Due to issue #35, I gave up on b), but it could still help me to do a) automatically, and save quite a few clicks.  The problem is that after this incredible number of folders are added via a simple import to the Photos app, using this package became incredibly slow.  Each call to `library.folder(uuid=month.uuid)` to retrieve a folder takes several seconds to return (see below).  This is also true if one just wants to iterate over folders with `library.folders`.

My current solution to mitigate the folder lookups was to use your other package (`osxphotos` - thx btw!) to do most of the read-only work and only call this package when I needed to write things.  The algorithm to implement this via this integration is like so:

1. Look up folder by UUID (about 25s on a Mac with M1 Max chip)
2. Create the album in subfolder from lookup in 1. (about 13s)
3. Lookup photos to transfer with `library.photos(uuid=...)` (very efficient, almost no time) and
4. Old album deletion (very efficient as well)

Am I overlooking something?  Is there a way to speed this up in these (difficult) conditions?

**Comment by RhetTbull** [comment]
I’ll take a look to see if there’s anything I can do.  This package uses AppleScript to interact with Photos and unfortunately the Photos AppleScript interface is very slow.

**Comment by anjos** [comment]
For example, the album creation requires a folder lookup. However, if the album could be created from the folder UUID directly, that would save the longest lookup already.

**Comment by RhetTbull** [comment]
Looking into the code I see that every interaction with a folder requires recursively traversing every folder and album in the library. As folders grow, this process slows down. Looping in AppleScript  is very slow. 

The reason the code does this is that the Photos AppleScript interface only exposes top-level folders. Thus, traversing the tree is required to find the child object. This is a limitation of Photos and how Apple has chosen to implement its AppleScript interface.  Note: in Mojave and earlier, it was possible to directly access child folders so this wasn’t necessary.

The following code gets called with every access to a `Folder` object:

https://github.com/RhetTbull/PhotoScript/blob/3d64c526c8edbccc16f4d7da64214c019d7b4bc8/photoscript/photoscript.applescript#L217-L250

Some possible solutions:

1. Short-circuit the tree traversal. Instead of finding all folders every time, return the desired folder object as soon as it’s found. This would create some improvement but if your folder was at the bottom of the tree, you’d still have to traverse the entire thing.
2. Dynamically build the AppleScript based on the folder tree. For example, if your album is organized thusly: `Folder A > Folder B > Album A` the AppleScript similar to this would be generated:

```applescript
album “Album A” of folder “Folder B” of folder “Folder A”
```

The first can likely be implemented fairly easily for a quick win. The second will take some considerable refactoring.

**Comment by RhetTbull** [comment]
> However, if the album could be created from the folder UUID directly, that would save the longest lookup already.

Unfortunately it cannot.  If you tell Photos (via AppleScript) to return the folder object for a given UUID but the folder is not a top level folder, Photos will raise an exception of “could not get folder for uuid XXX” as the main Photos object only has knowledge of top level folders.  There is an optimization already in the code for top levels (`PhotosLibrary().folder(name=“Folder A”, top_level=True`) but this isn’t always propagated internally.

If I implement #2 above and always use dynamic AppleScript for access, the problem goes away (but the engineering is more difficult).  I think that’s the right long-term solution though. However, in the case where you know the UUID but not the path of the folder or album, the code will still have to transverse the tree.

**Comment by RhetTbull** [comment]
So thinking through the interface, it might be something like:

`PhotosLibrary().album_by_path([“Folder A”, “Folder B”, “Album A”)`

And the same for `folder_by_path()`

Once created in this manner, an `Album` or `Folder` object would store the path and the dynamic AppleScript "accessor code".  A Folder or or Album object referenced by UUID or name (without path) would still need to do the tree traversal but in this case, there could be an AppleScript function that returns the path for using the next time around.

For the dynamic code, AppleScript does support an equivalent of python eval via [run script](https://developer.apple.com/library/archive/documentation/AppleScript/Conceptual/AppleScriptLangGuide/reference/ASLR_cmds.html#//apple_ref/doc/uid/TP40000983-CH216-SW36) so the code fragment could be passed around to the various AppleScript methods in [photoscript.applescript](https://github.com/RhetTbull/PhotoScript/blob/master/photoscript/photoscript.applescript)

**Comment by RhetTbull** [comment]
I have prototype AppleScript code work that dynamically builds the script to access a folder.  The following shows how `getFolderName()` and `setFolderName()` would be implemented in this new method. Will require major refactoring of the python interface. Instead of storing the UUID of the folder (and album), we'll need to store the AppleScript snippet needed to retrieve the folder (or album) as retrieved by `getFolderScriptfromPath` which will look like this for an example of `Folder1>SubFolder1>SubSubFolder1`: `folder id("E0CD4B6C-CB43-46A6-B8A3-67D1FB4D0F3D/L0/020") of folder id("CB051A4C-2CB7-4B90-B59B-08CC4D0C2823/L0/020") of folder id("88A5F8B8-5B9A-43C7-BB85-3952B81580EB/L0/020"`

Still need to get this working for Albums.

```applescript

on getTopLevelFolderID(folderName)
	(*	Returns the ID for a top level folder in Photos or missing value if not found 
	
		Args:
			folderName: string of top level folder name to find
	*)
	tell application "Photos"
		repeat with theFolder in folders
			if name of theFolder = folderName then
				return id of theFolder
			end if
		end repeat
	end tell
	return missing value
end getTopLevelFolderID

on getFolderScriptfromPath(folderPath)
	(*	Returns script snippet identifying the folder in Photos or missing value if not found
	
		Args:
			folderPath: list of folder paths in form {"Folder1", "SubFolder1", "SubSubFolder1", ...}
	
		Returns: script snippet in form: 
			"folder id(\"E0CD4B6C-CB43-46A6-B8A3-67D1FB4D0F3D/L0/020\") of folder id(\"CB051A4C-2CB7-4B90-B59B-08CC4D0C2823/L0/020\") of folder id(\"88A5F8B8-5B9A-43C7-BB85-3952B81580EB/L0/020\")"		
	*)
	set folderCount to count of folderPath
	if folderCount = 1 then
		set folderID to getTopLevelFolderID(item 1 of folderPath)
		return "folder id(\"" & folderID & "\")"
	end if
	
	set preamble to "
	on run(folderName)
		tell application \"Photos\"
		set theFolder to "
	
	set postamble to "
		 repeat with subFolder in folders of theFolder
		 	if name of subFolder as text is equal to folderName as text then
				return id of subFolder
			end if
		end repeat
		end tell
		return missing value
	end run
"
	set folderID to getTopLevelFolderID(item 1 of folderPath)
	set folderScript to ("folder id(\"" & folderID as text) & "\")"
	set folderList to items 2 through folderCount of folderPath
	repeat with folderName in folderList
		set theScript to preamble & folderScript & postamble
		set subFolderID to run script theScript with parameters {folderName}
		if subFolderID is missing value then
			return missing value
		end if
		set folderScript to ("folder id(\"" & subFolderID as text) & "\") of " & folderScript
	end repeat
	return folderScript
end getFolderScriptfromPath

on folderScript(folderIDScript, theScript)
	(*	Gets a folder identified by folderIDScript then runs theScript on this folder
	
		Args:
			folderIDScript: script snippet as returned by getFolderScriptfromPath
			theScript: script snippet to run; folder will be referenced as "theFolder"
			
		Example:
			To get name of folder: folderScript(folderIDScript, "return name of theFolder")
	*)
	set theScript to "
	on run()
		tell application \"Photos\"
			set theFolder to " & folderIDScript & " 
			" & theScript & "
		end tell
	end run
	"
	return run script theScript
end folderScript

on getFolderName(folderIDScript)
	(*	Return name of folder
	
		Args:
			folderIDScript: script snippet as returned by getFolderScriptfromPath
		
		Returns:
			name of folder as text
	*)
	return folderScript(folderIDScript, "return name of theFolder")
end getFolderName

on setFolderName(folderIDScript, theName)
	(* Set name of folder
	
		Args:
			folderIDScript: script snippet as returned by getFolderScriptfromPath
			theName: new name for folder as text
	*)
	return folderScript(folderIDScript, "set name of theFolder to \"" & theName & "\"")
end setFolderName

on getFolderUUID(folderIDScript)
	(*	Return UUID of folder
	
		Args:
			folderIDScript: script snippet as returned by getFolderScriptfromPath
		
		Returns:
			UUID of folder as text
	*)
	return folderScript(folderIDScript, "return id of theFolder")
end getFolderUUID

set parentFolder to getFolderScriptfromPath({"Folder1"})
set theName to getFolderName(parentFolder)
set theUUID to getFolderUUID(parentFolder)
log theName & " " & theUUID & " " & parentFolder

set subFolder to getFolderScriptfromPath({"Folder1", "SubFolder1", "SubSubFolder1"})
set theName to getFolderName(subFolder)
set theUUID to getFolderUUID(subFolder)
log theName & " " & theUUID & " " & subFolder

setFolderName(subFolder, "My new subfolder name")
```

**Comment by RhetTbull** [comment]
Making some progress on this but still have a fair amount of refactoring to do. I can now reliably look up folders without traversing the entire tree.

**Comment by anjos** [comment]
Thanks a lot for this!

**Comment by RhetTbull** [comment]
More progress.  About 2/3 of the way done.  This has turned out to be a major rewrite but the code will be much less "hacky" when done.

```
================================================================== short test summary info ===================================================================
FAILED tests/test_3_folder.py::test_folder_parent_id_not_toplevel - assert 'folder id("1FB9BF4B-3CF5-45DE-B4E7-C92047341196/L0/020")' == '1FB9BF4B-3CF5-45DE-B4E7-C92047341196/L0/020'
FAILED tests/test_3_folder.py::test_folder_parent_top_level - ValueError: One (and only one) of path, uuid, or idstring must be specified
FAILED tests/test_3_folder.py::test_folder_path - AssertionError: assert 2 == 1
FAILED tests/test_3_folder.py::test_folder_create_folder - applescript.ScriptError: Expected end of line but found class name. (-2741) app='Python' range=29309-29329
FAILED tests/test_3_folder.py::test_len_1 - applescript.ScriptError: Expected end of line but found identifier. (-2741) app='Python' range=29309-29329
FAILED tests/test_3_folder.py::test_len_2 - applescript.ScriptError: Expected end of line but found identifier. (-2741) app='Python' range=29309-29329
FAILED tests/test_3_folder.py::test_len_3 - applescript.ScriptError: Expected end of line but found identifier. (-2741) app='Python' range=29309-29329
==================================================== 7 failed, 21 passed, 1 warning in 230.66s (0:03:50) =====================================================
```

**Comment by RhetTbull** [comment]
All folder tests now passing with the newly refactored folder code.  A bit more cleanup and I'll be ready to push a beta release.

<details>
  <summary>Test Results</summary>
```
==================================================================== test session starts =====================================================================
platform darwin -- Python 3.11.0, pytest-7.2.0, pluggy-1.0.0 -- /Users/rhet/.pyenv/versions/3.11.0/envs/photoscript-3.11.0/bin/python
cachedir: .pytest_cache
rootdir: /Users/rhet/Dropbox/Code/photoscript
plugins: flaky-3.7.0
collected 28 items

tests/test_3_folder.py::test_folder_init_uuid PASSED                                                                                                   [  3%]
tests/test_3_folder.py::test_folder_init_osxphotos_uuid PASSED                                                                                         [  7%]
tests/test_3_folder.py::test_folder_init_bad_uuid PASSED                                                                                               [ 10%]
tests/test_3_folder.py::test_folder_init_bad_path PASSED                                                                                               [ 14%]
tests/test_3_folder.py::test_folder_init_bad_idstring PASSED                                                                                           [ 17%]
tests/test_3_folder.py::test_folder_id PASSED                                                                                                          [ 21%]
tests/test_3_folder.py::test_folder_uuid PASSED                                                                                                        [ 25%]
tests/test_3_folder.py::test_folder_name_title PASSED                                                                                                  [ 28%]
tests/test_3_folder.py::test_folder_name_setter PASSED                                                                                                 [ 32%]
tests/test_3_folder.py::test_folder_title_setter PASSED                                                                                                [ 35%]
tests/test_3_folder.py::test_folder_parent_id PASSED                                                                                                   [ 39%]
tests/test_3_folder.py::test_folder_parent_id_not_toplevel PASSED                                                                                      [ 42%]
tests/test_3_folder.py::test_folder_parent PASSED                                                                                                      [ 46%]
tests/test_3_folder.py::test_folder_parent_top_level PASSED                                                                                            [ 50%]
tests/test_3_folder.py::test_folder_path_str PASSED                                                                                                    [ 53%]
tests/test_3_folder.py::test_folder_path PASSED                                                                                                        [ 57%]
tests/test_3_folder.py::test_folder_albums PASSED                                                                                                      [ 60%]
tests/test_3_folder.py::test_folder_album PASSED                                                                                                       [ 64%]
tests/test_3_folder.py::test_folder_album_bad_name PASSED                                                                                              [ 67%]
tests/test_3_folder.py::test_folder_subfolders PASSED                                                                                                  [ 71%]
tests/test_3_folder.py::test_folder_subfolders_none PASSED                                                                                             [ 75%]
tests/test_3_folder.py::test_folder_folder PASSED                                                                                                      [ 78%]
tests/test_3_folder.py::test_folder_folder_none PASSED                                                                                                 [ 82%]
tests/test_3_folder.py::test_folder_create_album PASSED                                                                                                [ 85%]
tests/test_3_folder.py::test_folder_create_folder PASSED                                                                                               [ 89%]
tests/test_3_folder.py::test_len_1 PASSED                                                                                                              [ 92%]
tests/test_3_folder.py::test_len_2 PASSED                                                                                                              [ 96%]
tests/test_3_folder.py::test_len_3 PASSED                                                                                                              [100%]

=============================================================== 28 passed in 220.34s (0:03:40) ===============================================================
```
</details>

**Comment by RhetTbull** [comment]
Progress halted on this due to setting up a new Mac but now restarted. I finally upgraded my 2013 iMac to M1 Mac Mini but new computer running Ventura which broke all my tests. The PhotoScript code appears to work but none of the automated tests would run.  The tests need to copy a test library to the Pictures folder for testing and this was failing. Finally figured out AppleScript would only work on the test library if the test library was copied in the Finder.  Using `ditto` or `shutil.copy2` caused AppleScript to treat the test library as read only.  Very weird as this method worked on all previous macOS versions. So I had to write a copy function in AppleScript that scripted the Finder to do the copy.

**Comment by RhetTbull** [comment]
In [v0.3.0](https://github.com/RhetTbull/PhotoScript/releases/tag/v0.3.0) I've completely rewritten the folder code so it should be much faster now.

**Comment by RhetTbull** [comment]
@all-contributors please add @anjos for ideas, bug

**Comment by anjos** [comment]
Amazing job!  Thanks!
