### ISSUE TITLE
Set date/time of a photo

### ISSUE THREAD

**Issue by anjos** [RhetTbull/PhotoScript#40]
Here is a naïve question: is it possible to set the date and time of a picture using this library?

**Comment by RhetTbull** [comment]
Yes.  The following snippet changes the date/time of the first selected photo. You cannot change timezone. The date/time must be a timezone-naive `datetime` object in the local timezone.

```pycon
>>> import photoscript
>>> import datetime
>>> photo = photoscript.PhotosLibrary().selection[0]
>>> photo.date
datetime.datetime(2022, 11, 22, 0, 0)
>>> photo.date = datetime.datetime(2022,11,23,12,34,56)
>>> photo.date
datetime.datetime(2022, 11, 23, 12, 34, 56)
```

**Comment by RhetTbull** [comment]
For more advanced date/time manipulation, see the [timewarp](https://rhettbull.github.io/osxphotos/cli.html#osxphotos-timewarp) command of the [osxphotos](https://github.com/RhetTbull/osxphotos) tool which does allow manipulation of timezone.  (I'm the author of osxphotos as well).

**Comment by RhetTbull** [comment]
You can see all the properties of the `Photo` object [here](https://rhettbull.github.io/PhotoScript/reference.html#photoscript.Photo)

**Comment by anjos** [comment]
Thanks for this information.  I'll try this out soon.
