### ISSUE TITLE
Unattended "skip_duplicate_check" ? 

### ISSUE THREAD

**Issue by khurshid-alam** [RhetTbull/PhotoScript#49]
I like to have this unattended. Perhaps as a separate option like

```py

# (Silently skip importing if already exists)
skip_duplicate = True 

```

This is by default is "False" anyway. I am auto importing screenshots on Mac (Ventura). So if it tries to import again (some unforeseen situation) it shows a dialog. My current way is to comparing with filename_original. The script gets file_path as argument.

```py
#!#!/usr/env/python

import os
import sys
import datetime
import osxphotos
import photoscript


#file = "/Users/pcuser/Pictures/Desktop-Screenshots/Scarlet-Sparrow-Colored.jpg"

if sys.argv[1:]:
	file_path = sys.argv[1]
	if not os.path.exists(file_path):
		sys.exit(0)
	
	folder_path = os.path.dirname(file_path)
	album_name = os.path.basename(folder_path)

	if album_name == "Desktop-Screenshots":
		screen_shot = True
	dt = datetime.datetime.today() - datetime.timedelta(days=90)

	photosdb = osxphotos.PhotosDB()

       # Check photos added after 90 days ago and in album: Desktop-Screenshots
	results = photosdb.query(osxphotos.QueryOptions(in_album = album_name,
    						screenshot=screen_shot, added_after = dt))
	p_exists = [p.original_filename for p in results]
	print (p_exists)
	filename = os.path.basename(file_path)
	if filename not in p_exists:
		pl = photoscript.PhotosLibrary()
		pl.import_photos([file_path], album = pl.album(album_name))
		pl.quit()			
else:
	sys.exit(0)
```

**Comment by RhetTbull** [comment]
I'm sorry, I don't understand the issue. You can set `skip_duplicate_check=True` in your call to `import_photos()`. If you are saying you want PhotoScript to check for duplicates and skip them, sorry, that's outside the scope of PhotoScript which provides a Python interface that maps closely to the underlying AppleScript interface. With the exception of deleting from albums (not supported by AppleScript), PhotoScript does not any logic --  it's just a framework for you to build your own tools.

What I would do is to keep a running history of every file you've imported and check that first before importing. E.g. you could use my [sqlitekvstore](https://github.com/RhetTbull/sqlitekvstore).  

If you just want to periodically import, you could do this with [osxphotos](https://github.com/RhetTbull/osxphotos) using `osxphotos import`.  For example, the following would duplicate the functionality of your script:

`osxphotos import "/Users/pcuser/Pictures/Desktop-Screenshots/*" --skip-dups --album "{filepath.parent.name}"`

Or if the folder being processed is always "Desktop-Screenshots", just use:

`osxphotos import "/Users/pcuser/Pictures/Desktop-Screenshots/*" --skip-dups --album "Desktop-Screenshots"`

Use `osxphotos help import` for more information.

**Comment by khurshid-alam** [comment]
Thanks. What happens when skip_duplicate_check=True ?

it would import duplicate photos ?

**Comment by RhetTbull** [comment]
Yes, it would silently import duplicates in that case.

**Comment by khurshid-alam** [comment]
Thanks. I understood now. I end up using --skip-dups with osxphotos.
